/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as BaixarAppRouteImport } from './routes/baixar-app'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as RastreioPedidoIdRouteImport } from './routes/rastreio.$pedidoId'
import { Route as LojaSlugRouteImport } from './routes/loja.$slug'
import { Route as ClientesCidadeRouteImport } from './routes/clientes.$cidade'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as AuthenticatedLojaRouteRouteImport } from './routes/_authenticated/loja/route'
import { Route as AuthenticatedEntregadorRouteRouteImport } from './routes/_authenticated/entregador/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedLojaIndexRouteImport } from './routes/_authenticated/loja/index'
import { Route as AuthenticatedEntregadorIndexRouteImport } from './routes/_authenticated/entregador/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ApiPublicSendPushRouteImport } from './routes/api/public/send-push'
import { Route as ApiPublicPwaIconDotpngRouteImport } from './routes/api/public/pwa-icon[.]png'
import { Route as ApiPublicMpWebhookPlataformaRouteImport } from './routes/api/public/mp-webhook-plataforma'
import { Route as ApiPublicMpWebhookEntregadorRouteImport } from './routes/api/public/mp-webhook-entregador'
import { Route as ApiPublicMpWebhookRouteImport } from './routes/api/public/mp-webhook'
import { Route as ApiPublicManifestDotwebmanifestRouteImport } from './routes/api/public/manifest[.]webmanifest'
import { Route as AuthenticatedLojaSuporteRouteImport } from './routes/_authenticated/loja/suporte'
import { Route as AuthenticatedLojaProdutosRouteImport } from './routes/_authenticated/loja/produtos'
import { Route as AuthenticatedLojaPedidosRouteImport } from './routes/_authenticated/loja/pedidos'
import { Route as AuthenticatedLojaNovoPedidoRouteImport } from './routes/_authenticated/loja/novo-pedido'
import { Route as AuthenticatedLojaFinanceiroRouteImport } from './routes/_authenticated/loja/financeiro'
import { Route as AuthenticatedLojaEntregadoresRouteImport } from './routes/_authenticated/loja/entregadores'
import { Route as AuthenticatedLojaDashboardRouteImport } from './routes/_authenticated/loja/dashboard'
import { Route as AuthenticatedLojaConfiguracoesRouteImport } from './routes/_authenticated/loja/configuracoes'
import { Route as AuthenticatedLojaAgendamentosRouteImport } from './routes/_authenticated/loja/agendamentos'
import { Route as AuthenticatedEntregadorTurnosRouteImport } from './routes/_authenticated/entregador/turnos'
import { Route as AuthenticatedEntregadorPerfilRouteImport } from './routes/_authenticated/entregador/perfil'
import { Route as AuthenticatedEntregadorMensalidadeRouteImport } from './routes/_authenticated/entregador/mensalidade'
import { Route as AuthenticatedEntregadorHistoricoRouteImport } from './routes/_authenticated/entregador/historico'
import { Route as AuthenticatedEntregadorDisponiveisRouteImport } from './routes/_authenticated/entregador/disponiveis'
import { Route as AuthenticatedEntregadorCarteiraRouteImport } from './routes/_authenticated/entregador/carteira'
import { Route as AuthenticatedEntregadorAtivosRouteImport } from './routes/_authenticated/entregador/ativos'
import { Route as AuthenticatedAdminTarifasRouteImport } from './routes/_authenticated/admin/tarifas'
import { Route as AuthenticatedAdminSuporteRouteImport } from './routes/_authenticated/admin/suporte'
import { Route as AuthenticatedAdminRoteirizacaoRouteImport } from './routes/_authenticated/admin/roteirizacao'
import { Route as AuthenticatedAdminPlanosRouteImport } from './routes/_authenticated/admin/planos'
import { Route as AuthenticatedAdminPedidosRouteImport } from './routes/_authenticated/admin/pedidos'
import { Route as AuthenticatedAdminPasswordResetRouteImport } from './routes/_authenticated/admin/password-reset'
import { Route as AuthenticatedAdminNotificacaoSomLojaRouteImport } from './routes/_authenticated/admin/notificacao-som-loja'
import { Route as AuthenticatedAdminNotificacaoSomRouteImport } from './routes/_authenticated/admin/notificacao-som'
import { Route as AuthenticatedAdminLojasRouteImport } from './routes/_authenticated/admin/lojas'
import { Route as AuthenticatedAdminFinanceiroRouteImport } from './routes/_authenticated/admin/financeiro'
import { Route as AuthenticatedAdminEntregadoresRouteImport } from './routes/_authenticated/admin/entregadores'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedAdminCreditosEntregadorRouteImport } from './routes/_authenticated/admin/creditos-entregador'
import { Route as AuthenticatedAdminContratosRouteImport } from './routes/_authenticated/admin/contratos'
import { Route as AuthenticatedAdminCategoriasRouteImport } from './routes/_authenticated/admin/categorias'
import { Route as AuthenticatedAdminBrandingRouteImport } from './routes/_authenticated/admin/branding'
import { Route as AuthenticatedAdminAppApkRouteImport } from './routes/_authenticated/admin/app-apk'
import { Route as AuthenticatedAdminAnunciosRouteImport } from './routes/_authenticated/admin/anuncios'
import { Route as AuthenticatedAdminAlertasRouteImport } from './routes/_authenticated/admin/alertas'
import { Route as AuthenticatedAdminAdminsRouteImport } from './routes/_authenticated/admin/admins'
import { Route as ApiPublicMpWebhookLojaIdRouteImport } from './routes/api/public/mp-webhook.$lojaId'
import { Route as ApiPublicHooksMpPollPendentesRouteImport } from './routes/api/public/hooks/mp-poll-pendentes'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const BaixarAppRoute = BaixarAppRouteImport.update({
  id: '/baixar-app',
  path: '/baixar-app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const RastreioPedidoIdRoute = RastreioPedidoIdRouteImport.update({
  id: '/rastreio/$pedidoId',
  path: '/rastreio/$pedidoId',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaSlugRoute = LojaSlugRouteImport.update({
  id: '/loja/$slug',
  path: '/loja/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesCidadeRoute = ClientesCidadeRouteImport.update({
  id: '/clientes/$cidade',
  path: '/clientes/$cidade',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLojaRouteRoute = AuthenticatedLojaRouteRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntregadorRouteRoute =
  AuthenticatedEntregadorRouteRouteImport.update({
    id: '/entregador',
    path: '/entregador',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLojaIndexRoute = AuthenticatedLojaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedLojaRouteRoute,
} as any)
const AuthenticatedEntregadorIndexRoute =
  AuthenticatedEntregadorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEntregadorRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ApiPublicSendPushRoute = ApiPublicSendPushRouteImport.update({
  id: '/api/public/send-push',
  path: '/api/public/send-push',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPwaIconDotpngRoute = ApiPublicPwaIconDotpngRouteImport.update({
  id: '/api/public/pwa-icon.png',
  path: '/api/public/pwa-icon.png',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpWebhookPlataformaRoute =
  ApiPublicMpWebhookPlataformaRouteImport.update({
    id: '/api/public/mp-webhook-plataforma',
    path: '/api/public/mp-webhook-plataforma',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMpWebhookEntregadorRoute =
  ApiPublicMpWebhookEntregadorRouteImport.update({
    id: '/api/public/mp-webhook-entregador',
    path: '/api/public/mp-webhook-entregador',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMpWebhookRoute = ApiPublicMpWebhookRouteImport.update({
  id: '/api/public/mp-webhook',
  path: '/api/public/mp-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicManifestDotwebmanifestRoute =
  ApiPublicManifestDotwebmanifestRouteImport.update({
    id: '/api/public/manifest.webmanifest',
    path: '/api/public/manifest.webmanifest',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedLojaSuporteRoute =
  AuthenticatedLojaSuporteRouteImport.update({
    id: '/suporte',
    path: '/suporte',
    getParentRoute: () => AuthenticatedLojaRouteRoute,
  } as any)
const AuthenticatedLojaProdutosRoute =
  AuthenticatedLojaProdutosRouteImport.update({
    id: '/produtos',
    path: '/produtos',
    getParentRoute: () => AuthenticatedLojaRouteRoute,
  } as any)
const AuthenticatedLojaPedidosRoute =
  AuthenticatedLojaPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AuthenticatedLojaRouteRoute,
  } as any)
const AuthenticatedLojaNovoPedidoRoute =
  AuthenticatedLojaNovoPedidoRouteImport.update({
    id: '/novo-pedido',
    path: '/novo-pedido',
    getParentRoute: () => AuthenticatedLojaRouteRoute,
  } as any)
const AuthenticatedLojaFinanceiroRoute =
  AuthenticatedLojaFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedLojaRouteRoute,
  } as any)
const AuthenticatedLojaEntregadoresRoute =
  AuthenticatedLojaEntregadoresRouteImport.update({
    id: '/entregadores',
    path: '/entregadores',
    getParentRoute: () => AuthenticatedLojaRouteRoute,
  } as any)
const AuthenticatedLojaDashboardRoute =
  AuthenticatedLojaDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedLojaRouteRoute,
  } as any)
const AuthenticatedLojaConfiguracoesRoute =
  AuthenticatedLojaConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedLojaRouteRoute,
  } as any)
const AuthenticatedLojaAgendamentosRoute =
  AuthenticatedLojaAgendamentosRouteImport.update({
    id: '/agendamentos',
    path: '/agendamentos',
    getParentRoute: () => AuthenticatedLojaRouteRoute,
  } as any)
const AuthenticatedEntregadorTurnosRoute =
  AuthenticatedEntregadorTurnosRouteImport.update({
    id: '/turnos',
    path: '/turnos',
    getParentRoute: () => AuthenticatedEntregadorRouteRoute,
  } as any)
const AuthenticatedEntregadorPerfilRoute =
  AuthenticatedEntregadorPerfilRouteImport.update({
    id: '/perfil',
    path: '/perfil',
    getParentRoute: () => AuthenticatedEntregadorRouteRoute,
  } as any)
const AuthenticatedEntregadorMensalidadeRoute =
  AuthenticatedEntregadorMensalidadeRouteImport.update({
    id: '/mensalidade',
    path: '/mensalidade',
    getParentRoute: () => AuthenticatedEntregadorRouteRoute,
  } as any)
const AuthenticatedEntregadorHistoricoRoute =
  AuthenticatedEntregadorHistoricoRouteImport.update({
    id: '/historico',
    path: '/historico',
    getParentRoute: () => AuthenticatedEntregadorRouteRoute,
  } as any)
const AuthenticatedEntregadorDisponiveisRoute =
  AuthenticatedEntregadorDisponiveisRouteImport.update({
    id: '/disponiveis',
    path: '/disponiveis',
    getParentRoute: () => AuthenticatedEntregadorRouteRoute,
  } as any)
const AuthenticatedEntregadorCarteiraRoute =
  AuthenticatedEntregadorCarteiraRouteImport.update({
    id: '/carteira',
    path: '/carteira',
    getParentRoute: () => AuthenticatedEntregadorRouteRoute,
  } as any)
const AuthenticatedEntregadorAtivosRoute =
  AuthenticatedEntregadorAtivosRouteImport.update({
    id: '/ativos',
    path: '/ativos',
    getParentRoute: () => AuthenticatedEntregadorRouteRoute,
  } as any)
const AuthenticatedAdminTarifasRoute =
  AuthenticatedAdminTarifasRouteImport.update({
    id: '/tarifas',
    path: '/tarifas',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSuporteRoute =
  AuthenticatedAdminSuporteRouteImport.update({
    id: '/suporte',
    path: '/suporte',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRoteirizacaoRoute =
  AuthenticatedAdminRoteirizacaoRouteImport.update({
    id: '/roteirizacao',
    path: '/roteirizacao',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPlanosRoute =
  AuthenticatedAdminPlanosRouteImport.update({
    id: '/planos',
    path: '/planos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPedidosRoute =
  AuthenticatedAdminPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPasswordResetRoute =
  AuthenticatedAdminPasswordResetRouteImport.update({
    id: '/password-reset',
    path: '/password-reset',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminNotificacaoSomLojaRoute =
  AuthenticatedAdminNotificacaoSomLojaRouteImport.update({
    id: '/notificacao-som-loja',
    path: '/notificacao-som-loja',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminNotificacaoSomRoute =
  AuthenticatedAdminNotificacaoSomRouteImport.update({
    id: '/notificacao-som',
    path: '/notificacao-som',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLojasRoute = AuthenticatedAdminLojasRouteImport.update({
  id: '/lojas',
  path: '/lojas',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminFinanceiroRoute =
  AuthenticatedAdminFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEntregadoresRoute =
  AuthenticatedAdminEntregadoresRouteImport.update({
    id: '/entregadores',
    path: '/entregadores',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCreditosEntregadorRoute =
  AuthenticatedAdminCreditosEntregadorRouteImport.update({
    id: '/creditos-entregador',
    path: '/creditos-entregador',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminContratosRoute =
  AuthenticatedAdminContratosRouteImport.update({
    id: '/contratos',
    path: '/contratos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCategoriasRoute =
  AuthenticatedAdminCategoriasRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBrandingRoute =
  AuthenticatedAdminBrandingRouteImport.update({
    id: '/branding',
    path: '/branding',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAppApkRoute =
  AuthenticatedAdminAppApkRouteImport.update({
    id: '/app-apk',
    path: '/app-apk',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAnunciosRoute =
  AuthenticatedAdminAnunciosRouteImport.update({
    id: '/anuncios',
    path: '/anuncios',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAlertasRoute =
  AuthenticatedAdminAlertasRouteImport.update({
    id: '/alertas',
    path: '/alertas',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminsRoute =
  AuthenticatedAdminAdminsRouteImport.update({
    id: '/admins',
    path: '/admins',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const ApiPublicMpWebhookLojaIdRoute =
  ApiPublicMpWebhookLojaIdRouteImport.update({
    id: '/$lojaId',
    path: '/$lojaId',
    getParentRoute: () => ApiPublicMpWebhookRoute,
  } as any)
const ApiPublicHooksMpPollPendentesRoute =
  ApiPublicHooksMpPollPendentesRouteImport.update({
    id: '/api/public/hooks/mp-poll-pendentes',
    path: '/api/public/hooks/mp-poll-pendentes',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/baixar-app': typeof BaixarAppRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/entregador': typeof AuthenticatedEntregadorRouteRouteWithChildren
  '/loja': typeof AuthenticatedLojaRouteRouteWithChildren
  '/c/$slug': typeof CSlugRoute
  '/clientes/$cidade': typeof ClientesCidadeRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/rastreio/$pedidoId': typeof RastreioPedidoIdRoute
  '/clientes/': typeof ClientesIndexRoute
  '/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/admin/alertas': typeof AuthenticatedAdminAlertasRoute
  '/admin/anuncios': typeof AuthenticatedAdminAnunciosRoute
  '/admin/app-apk': typeof AuthenticatedAdminAppApkRoute
  '/admin/branding': typeof AuthenticatedAdminBrandingRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/contratos': typeof AuthenticatedAdminContratosRoute
  '/admin/creditos-entregador': typeof AuthenticatedAdminCreditosEntregadorRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/entregadores': typeof AuthenticatedAdminEntregadoresRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/lojas': typeof AuthenticatedAdminLojasRoute
  '/admin/notificacao-som': typeof AuthenticatedAdminNotificacaoSomRoute
  '/admin/notificacao-som-loja': typeof AuthenticatedAdminNotificacaoSomLojaRoute
  '/admin/password-reset': typeof AuthenticatedAdminPasswordResetRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/planos': typeof AuthenticatedAdminPlanosRoute
  '/admin/roteirizacao': typeof AuthenticatedAdminRoteirizacaoRoute
  '/admin/suporte': typeof AuthenticatedAdminSuporteRoute
  '/admin/tarifas': typeof AuthenticatedAdminTarifasRoute
  '/entregador/ativos': typeof AuthenticatedEntregadorAtivosRoute
  '/entregador/carteira': typeof AuthenticatedEntregadorCarteiraRoute
  '/entregador/disponiveis': typeof AuthenticatedEntregadorDisponiveisRoute
  '/entregador/historico': typeof AuthenticatedEntregadorHistoricoRoute
  '/entregador/mensalidade': typeof AuthenticatedEntregadorMensalidadeRoute
  '/entregador/perfil': typeof AuthenticatedEntregadorPerfilRoute
  '/entregador/turnos': typeof AuthenticatedEntregadorTurnosRoute
  '/loja/agendamentos': typeof AuthenticatedLojaAgendamentosRoute
  '/loja/configuracoes': typeof AuthenticatedLojaConfiguracoesRoute
  '/loja/dashboard': typeof AuthenticatedLojaDashboardRoute
  '/loja/entregadores': typeof AuthenticatedLojaEntregadoresRoute
  '/loja/financeiro': typeof AuthenticatedLojaFinanceiroRoute
  '/loja/novo-pedido': typeof AuthenticatedLojaNovoPedidoRoute
  '/loja/pedidos': typeof AuthenticatedLojaPedidosRoute
  '/loja/produtos': typeof AuthenticatedLojaProdutosRoute
  '/loja/suporte': typeof AuthenticatedLojaSuporteRoute
  '/api/public/manifest.webmanifest': typeof ApiPublicManifestDotwebmanifestRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRouteWithChildren
  '/api/public/mp-webhook-entregador': typeof ApiPublicMpWebhookEntregadorRoute
  '/api/public/mp-webhook-plataforma': typeof ApiPublicMpWebhookPlataformaRoute
  '/api/public/pwa-icon.png': typeof ApiPublicPwaIconDotpngRoute
  '/api/public/send-push': typeof ApiPublicSendPushRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/entregador/': typeof AuthenticatedEntregadorIndexRoute
  '/loja/': typeof AuthenticatedLojaIndexRoute
  '/api/public/hooks/mp-poll-pendentes': typeof ApiPublicHooksMpPollPendentesRoute
  '/api/public/mp-webhook/$lojaId': typeof ApiPublicMpWebhookLojaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/baixar-app': typeof BaixarAppRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/c/$slug': typeof CSlugRoute
  '/clientes/$cidade': typeof ClientesCidadeRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/rastreio/$pedidoId': typeof RastreioPedidoIdRoute
  '/clientes': typeof ClientesIndexRoute
  '/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/admin/alertas': typeof AuthenticatedAdminAlertasRoute
  '/admin/anuncios': typeof AuthenticatedAdminAnunciosRoute
  '/admin/app-apk': typeof AuthenticatedAdminAppApkRoute
  '/admin/branding': typeof AuthenticatedAdminBrandingRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/contratos': typeof AuthenticatedAdminContratosRoute
  '/admin/creditos-entregador': typeof AuthenticatedAdminCreditosEntregadorRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/entregadores': typeof AuthenticatedAdminEntregadoresRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/lojas': typeof AuthenticatedAdminLojasRoute
  '/admin/notificacao-som': typeof AuthenticatedAdminNotificacaoSomRoute
  '/admin/notificacao-som-loja': typeof AuthenticatedAdminNotificacaoSomLojaRoute
  '/admin/password-reset': typeof AuthenticatedAdminPasswordResetRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/planos': typeof AuthenticatedAdminPlanosRoute
  '/admin/roteirizacao': typeof AuthenticatedAdminRoteirizacaoRoute
  '/admin/suporte': typeof AuthenticatedAdminSuporteRoute
  '/admin/tarifas': typeof AuthenticatedAdminTarifasRoute
  '/entregador/ativos': typeof AuthenticatedEntregadorAtivosRoute
  '/entregador/carteira': typeof AuthenticatedEntregadorCarteiraRoute
  '/entregador/disponiveis': typeof AuthenticatedEntregadorDisponiveisRoute
  '/entregador/historico': typeof AuthenticatedEntregadorHistoricoRoute
  '/entregador/mensalidade': typeof AuthenticatedEntregadorMensalidadeRoute
  '/entregador/perfil': typeof AuthenticatedEntregadorPerfilRoute
  '/entregador/turnos': typeof AuthenticatedEntregadorTurnosRoute
  '/loja/agendamentos': typeof AuthenticatedLojaAgendamentosRoute
  '/loja/configuracoes': typeof AuthenticatedLojaConfiguracoesRoute
  '/loja/dashboard': typeof AuthenticatedLojaDashboardRoute
  '/loja/entregadores': typeof AuthenticatedLojaEntregadoresRoute
  '/loja/financeiro': typeof AuthenticatedLojaFinanceiroRoute
  '/loja/novo-pedido': typeof AuthenticatedLojaNovoPedidoRoute
  '/loja/pedidos': typeof AuthenticatedLojaPedidosRoute
  '/loja/produtos': typeof AuthenticatedLojaProdutosRoute
  '/loja/suporte': typeof AuthenticatedLojaSuporteRoute
  '/api/public/manifest.webmanifest': typeof ApiPublicManifestDotwebmanifestRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRouteWithChildren
  '/api/public/mp-webhook-entregador': typeof ApiPublicMpWebhookEntregadorRoute
  '/api/public/mp-webhook-plataforma': typeof ApiPublicMpWebhookPlataformaRoute
  '/api/public/pwa-icon.png': typeof ApiPublicPwaIconDotpngRoute
  '/api/public/send-push': typeof ApiPublicSendPushRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/entregador': typeof AuthenticatedEntregadorIndexRoute
  '/loja': typeof AuthenticatedLojaIndexRoute
  '/api/public/hooks/mp-poll-pendentes': typeof ApiPublicHooksMpPollPendentesRoute
  '/api/public/mp-webhook/$lojaId': typeof ApiPublicMpWebhookLojaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/baixar-app': typeof BaixarAppRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/entregador': typeof AuthenticatedEntregadorRouteRouteWithChildren
  '/_authenticated/loja': typeof AuthenticatedLojaRouteRouteWithChildren
  '/c/$slug': typeof CSlugRoute
  '/clientes/$cidade': typeof ClientesCidadeRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/rastreio/$pedidoId': typeof RastreioPedidoIdRoute
  '/clientes/': typeof ClientesIndexRoute
  '/_authenticated/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/_authenticated/admin/alertas': typeof AuthenticatedAdminAlertasRoute
  '/_authenticated/admin/anuncios': typeof AuthenticatedAdminAnunciosRoute
  '/_authenticated/admin/app-apk': typeof AuthenticatedAdminAppApkRoute
  '/_authenticated/admin/branding': typeof AuthenticatedAdminBrandingRoute
  '/_authenticated/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/_authenticated/admin/contratos': typeof AuthenticatedAdminContratosRoute
  '/_authenticated/admin/creditos-entregador': typeof AuthenticatedAdminCreditosEntregadorRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/entregadores': typeof AuthenticatedAdminEntregadoresRoute
  '/_authenticated/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/_authenticated/admin/lojas': typeof AuthenticatedAdminLojasRoute
  '/_authenticated/admin/notificacao-som': typeof AuthenticatedAdminNotificacaoSomRoute
  '/_authenticated/admin/notificacao-som-loja': typeof AuthenticatedAdminNotificacaoSomLojaRoute
  '/_authenticated/admin/password-reset': typeof AuthenticatedAdminPasswordResetRoute
  '/_authenticated/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/_authenticated/admin/planos': typeof AuthenticatedAdminPlanosRoute
  '/_authenticated/admin/roteirizacao': typeof AuthenticatedAdminRoteirizacaoRoute
  '/_authenticated/admin/suporte': typeof AuthenticatedAdminSuporteRoute
  '/_authenticated/admin/tarifas': typeof AuthenticatedAdminTarifasRoute
  '/_authenticated/entregador/ativos': typeof AuthenticatedEntregadorAtivosRoute
  '/_authenticated/entregador/carteira': typeof AuthenticatedEntregadorCarteiraRoute
  '/_authenticated/entregador/disponiveis': typeof AuthenticatedEntregadorDisponiveisRoute
  '/_authenticated/entregador/historico': typeof AuthenticatedEntregadorHistoricoRoute
  '/_authenticated/entregador/mensalidade': typeof AuthenticatedEntregadorMensalidadeRoute
  '/_authenticated/entregador/perfil': typeof AuthenticatedEntregadorPerfilRoute
  '/_authenticated/entregador/turnos': typeof AuthenticatedEntregadorTurnosRoute
  '/_authenticated/loja/agendamentos': typeof AuthenticatedLojaAgendamentosRoute
  '/_authenticated/loja/configuracoes': typeof AuthenticatedLojaConfiguracoesRoute
  '/_authenticated/loja/dashboard': typeof AuthenticatedLojaDashboardRoute
  '/_authenticated/loja/entregadores': typeof AuthenticatedLojaEntregadoresRoute
  '/_authenticated/loja/financeiro': typeof AuthenticatedLojaFinanceiroRoute
  '/_authenticated/loja/novo-pedido': typeof AuthenticatedLojaNovoPedidoRoute
  '/_authenticated/loja/pedidos': typeof AuthenticatedLojaPedidosRoute
  '/_authenticated/loja/produtos': typeof AuthenticatedLojaProdutosRoute
  '/_authenticated/loja/suporte': typeof AuthenticatedLojaSuporteRoute
  '/api/public/manifest.webmanifest': typeof ApiPublicManifestDotwebmanifestRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRouteWithChildren
  '/api/public/mp-webhook-entregador': typeof ApiPublicMpWebhookEntregadorRoute
  '/api/public/mp-webhook-plataforma': typeof ApiPublicMpWebhookPlataformaRoute
  '/api/public/pwa-icon.png': typeof ApiPublicPwaIconDotpngRoute
  '/api/public/send-push': typeof ApiPublicSendPushRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/entregador/': typeof AuthenticatedEntregadorIndexRoute
  '/_authenticated/loja/': typeof AuthenticatedLojaIndexRoute
  '/api/public/hooks/mp-poll-pendentes': typeof ApiPublicHooksMpPollPendentesRoute
  '/api/public/mp-webhook/$lojaId': typeof ApiPublicMpWebhookLojaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/baixar-app'
    | '/cadastro'
    | '/login'
    | '/reset-password'
    | '/admin'
    | '/entregador'
    | '/loja'
    | '/c/$slug'
    | '/clientes/$cidade'
    | '/loja/$slug'
    | '/rastreio/$pedidoId'
    | '/clientes/'
    | '/admin/admins'
    | '/admin/alertas'
    | '/admin/anuncios'
    | '/admin/app-apk'
    | '/admin/branding'
    | '/admin/categorias'
    | '/admin/contratos'
    | '/admin/creditos-entregador'
    | '/admin/dashboard'
    | '/admin/entregadores'
    | '/admin/financeiro'
    | '/admin/lojas'
    | '/admin/notificacao-som'
    | '/admin/notificacao-som-loja'
    | '/admin/password-reset'
    | '/admin/pedidos'
    | '/admin/planos'
    | '/admin/roteirizacao'
    | '/admin/suporte'
    | '/admin/tarifas'
    | '/entregador/ativos'
    | '/entregador/carteira'
    | '/entregador/disponiveis'
    | '/entregador/historico'
    | '/entregador/mensalidade'
    | '/entregador/perfil'
    | '/entregador/turnos'
    | '/loja/agendamentos'
    | '/loja/configuracoes'
    | '/loja/dashboard'
    | '/loja/entregadores'
    | '/loja/financeiro'
    | '/loja/novo-pedido'
    | '/loja/pedidos'
    | '/loja/produtos'
    | '/loja/suporte'
    | '/api/public/manifest.webmanifest'
    | '/api/public/mp-webhook'
    | '/api/public/mp-webhook-entregador'
    | '/api/public/mp-webhook-plataforma'
    | '/api/public/pwa-icon.png'
    | '/api/public/send-push'
    | '/admin/'
    | '/entregador/'
    | '/loja/'
    | '/api/public/hooks/mp-poll-pendentes'
    | '/api/public/mp-webhook/$lojaId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/baixar-app'
    | '/cadastro'
    | '/login'
    | '/reset-password'
    | '/c/$slug'
    | '/clientes/$cidade'
    | '/loja/$slug'
    | '/rastreio/$pedidoId'
    | '/clientes'
    | '/admin/admins'
    | '/admin/alertas'
    | '/admin/anuncios'
    | '/admin/app-apk'
    | '/admin/branding'
    | '/admin/categorias'
    | '/admin/contratos'
    | '/admin/creditos-entregador'
    | '/admin/dashboard'
    | '/admin/entregadores'
    | '/admin/financeiro'
    | '/admin/lojas'
    | '/admin/notificacao-som'
    | '/admin/notificacao-som-loja'
    | '/admin/password-reset'
    | '/admin/pedidos'
    | '/admin/planos'
    | '/admin/roteirizacao'
    | '/admin/suporte'
    | '/admin/tarifas'
    | '/entregador/ativos'
    | '/entregador/carteira'
    | '/entregador/disponiveis'
    | '/entregador/historico'
    | '/entregador/mensalidade'
    | '/entregador/perfil'
    | '/entregador/turnos'
    | '/loja/agendamentos'
    | '/loja/configuracoes'
    | '/loja/dashboard'
    | '/loja/entregadores'
    | '/loja/financeiro'
    | '/loja/novo-pedido'
    | '/loja/pedidos'
    | '/loja/produtos'
    | '/loja/suporte'
    | '/api/public/manifest.webmanifest'
    | '/api/public/mp-webhook'
    | '/api/public/mp-webhook-entregador'
    | '/api/public/mp-webhook-plataforma'
    | '/api/public/pwa-icon.png'
    | '/api/public/send-push'
    | '/admin'
    | '/entregador'
    | '/loja'
    | '/api/public/hooks/mp-poll-pendentes'
    | '/api/public/mp-webhook/$lojaId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/baixar-app'
    | '/cadastro'
    | '/login'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/entregador'
    | '/_authenticated/loja'
    | '/c/$slug'
    | '/clientes/$cidade'
    | '/loja/$slug'
    | '/rastreio/$pedidoId'
    | '/clientes/'
    | '/_authenticated/admin/admins'
    | '/_authenticated/admin/alertas'
    | '/_authenticated/admin/anuncios'
    | '/_authenticated/admin/app-apk'
    | '/_authenticated/admin/branding'
    | '/_authenticated/admin/categorias'
    | '/_authenticated/admin/contratos'
    | '/_authenticated/admin/creditos-entregador'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/entregadores'
    | '/_authenticated/admin/financeiro'
    | '/_authenticated/admin/lojas'
    | '/_authenticated/admin/notificacao-som'
    | '/_authenticated/admin/notificacao-som-loja'
    | '/_authenticated/admin/password-reset'
    | '/_authenticated/admin/pedidos'
    | '/_authenticated/admin/planos'
    | '/_authenticated/admin/roteirizacao'
    | '/_authenticated/admin/suporte'
    | '/_authenticated/admin/tarifas'
    | '/_authenticated/entregador/ativos'
    | '/_authenticated/entregador/carteira'
    | '/_authenticated/entregador/disponiveis'
    | '/_authenticated/entregador/historico'
    | '/_authenticated/entregador/mensalidade'
    | '/_authenticated/entregador/perfil'
    | '/_authenticated/entregador/turnos'
    | '/_authenticated/loja/agendamentos'
    | '/_authenticated/loja/configuracoes'
    | '/_authenticated/loja/dashboard'
    | '/_authenticated/loja/entregadores'
    | '/_authenticated/loja/financeiro'
    | '/_authenticated/loja/novo-pedido'
    | '/_authenticated/loja/pedidos'
    | '/_authenticated/loja/produtos'
    | '/_authenticated/loja/suporte'
    | '/api/public/manifest.webmanifest'
    | '/api/public/mp-webhook'
    | '/api/public/mp-webhook-entregador'
    | '/api/public/mp-webhook-plataforma'
    | '/api/public/pwa-icon.png'
    | '/api/public/send-push'
    | '/_authenticated/admin/'
    | '/_authenticated/entregador/'
    | '/_authenticated/loja/'
    | '/api/public/hooks/mp-poll-pendentes'
    | '/api/public/mp-webhook/$lojaId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  BaixarAppRoute: typeof BaixarAppRoute
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  CSlugRoute: typeof CSlugRoute
  ClientesCidadeRoute: typeof ClientesCidadeRoute
  LojaSlugRoute: typeof LojaSlugRoute
  RastreioPedidoIdRoute: typeof RastreioPedidoIdRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
  ApiPublicManifestDotwebmanifestRoute: typeof ApiPublicManifestDotwebmanifestRoute
  ApiPublicMpWebhookRoute: typeof ApiPublicMpWebhookRouteWithChildren
  ApiPublicMpWebhookEntregadorRoute: typeof ApiPublicMpWebhookEntregadorRoute
  ApiPublicMpWebhookPlataformaRoute: typeof ApiPublicMpWebhookPlataformaRoute
  ApiPublicPwaIconDotpngRoute: typeof ApiPublicPwaIconDotpngRoute
  ApiPublicSendPushRoute: typeof ApiPublicSendPushRoute
  ApiPublicHooksMpPollPendentesRoute: typeof ApiPublicHooksMpPollPendentesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baixar-app': {
      id: '/baixar-app'
      path: '/baixar-app'
      fullPath: '/baixar-app'
      preLoaderRoute: typeof BaixarAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rastreio/$pedidoId': {
      id: '/rastreio/$pedidoId'
      path: '/rastreio/$pedidoId'
      fullPath: '/rastreio/$pedidoId'
      preLoaderRoute: typeof RastreioPedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/$slug': {
      id: '/loja/$slug'
      path: '/loja/$slug'
      fullPath: '/loja/$slug'
      preLoaderRoute: typeof LojaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$cidade': {
      id: '/clientes/$cidade'
      path: '/clientes/$cidade'
      fullPath: '/clientes/$cidade'
      preLoaderRoute: typeof ClientesCidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/loja': {
      id: '/_authenticated/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof AuthenticatedLojaRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entregador': {
      id: '/_authenticated/entregador'
      path: '/entregador'
      fullPath: '/entregador'
      preLoaderRoute: typeof AuthenticatedEntregadorRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loja/': {
      id: '/_authenticated/loja/'
      path: '/'
      fullPath: '/loja/'
      preLoaderRoute: typeof AuthenticatedLojaIndexRouteImport
      parentRoute: typeof AuthenticatedLojaRouteRoute
    }
    '/_authenticated/entregador/': {
      id: '/_authenticated/entregador/'
      path: '/'
      fullPath: '/entregador/'
      preLoaderRoute: typeof AuthenticatedEntregadorIndexRouteImport
      parentRoute: typeof AuthenticatedEntregadorRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/send-push': {
      id: '/api/public/send-push'
      path: '/api/public/send-push'
      fullPath: '/api/public/send-push'
      preLoaderRoute: typeof ApiPublicSendPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pwa-icon.png': {
      id: '/api/public/pwa-icon.png'
      path: '/api/public/pwa-icon.png'
      fullPath: '/api/public/pwa-icon.png'
      preLoaderRoute: typeof ApiPublicPwaIconDotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mp-webhook-plataforma': {
      id: '/api/public/mp-webhook-plataforma'
      path: '/api/public/mp-webhook-plataforma'
      fullPath: '/api/public/mp-webhook-plataforma'
      preLoaderRoute: typeof ApiPublicMpWebhookPlataformaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mp-webhook-entregador': {
      id: '/api/public/mp-webhook-entregador'
      path: '/api/public/mp-webhook-entregador'
      fullPath: '/api/public/mp-webhook-entregador'
      preLoaderRoute: typeof ApiPublicMpWebhookEntregadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mp-webhook': {
      id: '/api/public/mp-webhook'
      path: '/api/public/mp-webhook'
      fullPath: '/api/public/mp-webhook'
      preLoaderRoute: typeof ApiPublicMpWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/manifest.webmanifest': {
      id: '/api/public/manifest.webmanifest'
      path: '/api/public/manifest.webmanifest'
      fullPath: '/api/public/manifest.webmanifest'
      preLoaderRoute: typeof ApiPublicManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/loja/suporte': {
      id: '/_authenticated/loja/suporte'
      path: '/suporte'
      fullPath: '/loja/suporte'
      preLoaderRoute: typeof AuthenticatedLojaSuporteRouteImport
      parentRoute: typeof AuthenticatedLojaRouteRoute
    }
    '/_authenticated/loja/produtos': {
      id: '/_authenticated/loja/produtos'
      path: '/produtos'
      fullPath: '/loja/produtos'
      preLoaderRoute: typeof AuthenticatedLojaProdutosRouteImport
      parentRoute: typeof AuthenticatedLojaRouteRoute
    }
    '/_authenticated/loja/pedidos': {
      id: '/_authenticated/loja/pedidos'
      path: '/pedidos'
      fullPath: '/loja/pedidos'
      preLoaderRoute: typeof AuthenticatedLojaPedidosRouteImport
      parentRoute: typeof AuthenticatedLojaRouteRoute
    }
    '/_authenticated/loja/novo-pedido': {
      id: '/_authenticated/loja/novo-pedido'
      path: '/novo-pedido'
      fullPath: '/loja/novo-pedido'
      preLoaderRoute: typeof AuthenticatedLojaNovoPedidoRouteImport
      parentRoute: typeof AuthenticatedLojaRouteRoute
    }
    '/_authenticated/loja/financeiro': {
      id: '/_authenticated/loja/financeiro'
      path: '/financeiro'
      fullPath: '/loja/financeiro'
      preLoaderRoute: typeof AuthenticatedLojaFinanceiroRouteImport
      parentRoute: typeof AuthenticatedLojaRouteRoute
    }
    '/_authenticated/loja/entregadores': {
      id: '/_authenticated/loja/entregadores'
      path: '/entregadores'
      fullPath: '/loja/entregadores'
      preLoaderRoute: typeof AuthenticatedLojaEntregadoresRouteImport
      parentRoute: typeof AuthenticatedLojaRouteRoute
    }
    '/_authenticated/loja/dashboard': {
      id: '/_authenticated/loja/dashboard'
      path: '/dashboard'
      fullPath: '/loja/dashboard'
      preLoaderRoute: typeof AuthenticatedLojaDashboardRouteImport
      parentRoute: typeof AuthenticatedLojaRouteRoute
    }
    '/_authenticated/loja/configuracoes': {
      id: '/_authenticated/loja/configuracoes'
      path: '/configuracoes'
      fullPath: '/loja/configuracoes'
      preLoaderRoute: typeof AuthenticatedLojaConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedLojaRouteRoute
    }
    '/_authenticated/loja/agendamentos': {
      id: '/_authenticated/loja/agendamentos'
      path: '/agendamentos'
      fullPath: '/loja/agendamentos'
      preLoaderRoute: typeof AuthenticatedLojaAgendamentosRouteImport
      parentRoute: typeof AuthenticatedLojaRouteRoute
    }
    '/_authenticated/entregador/turnos': {
      id: '/_authenticated/entregador/turnos'
      path: '/turnos'
      fullPath: '/entregador/turnos'
      preLoaderRoute: typeof AuthenticatedEntregadorTurnosRouteImport
      parentRoute: typeof AuthenticatedEntregadorRouteRoute
    }
    '/_authenticated/entregador/perfil': {
      id: '/_authenticated/entregador/perfil'
      path: '/perfil'
      fullPath: '/entregador/perfil'
      preLoaderRoute: typeof AuthenticatedEntregadorPerfilRouteImport
      parentRoute: typeof AuthenticatedEntregadorRouteRoute
    }
    '/_authenticated/entregador/mensalidade': {
      id: '/_authenticated/entregador/mensalidade'
      path: '/mensalidade'
      fullPath: '/entregador/mensalidade'
      preLoaderRoute: typeof AuthenticatedEntregadorMensalidadeRouteImport
      parentRoute: typeof AuthenticatedEntregadorRouteRoute
    }
    '/_authenticated/entregador/historico': {
      id: '/_authenticated/entregador/historico'
      path: '/historico'
      fullPath: '/entregador/historico'
      preLoaderRoute: typeof AuthenticatedEntregadorHistoricoRouteImport
      parentRoute: typeof AuthenticatedEntregadorRouteRoute
    }
    '/_authenticated/entregador/disponiveis': {
      id: '/_authenticated/entregador/disponiveis'
      path: '/disponiveis'
      fullPath: '/entregador/disponiveis'
      preLoaderRoute: typeof AuthenticatedEntregadorDisponiveisRouteImport
      parentRoute: typeof AuthenticatedEntregadorRouteRoute
    }
    '/_authenticated/entregador/carteira': {
      id: '/_authenticated/entregador/carteira'
      path: '/carteira'
      fullPath: '/entregador/carteira'
      preLoaderRoute: typeof AuthenticatedEntregadorCarteiraRouteImport
      parentRoute: typeof AuthenticatedEntregadorRouteRoute
    }
    '/_authenticated/entregador/ativos': {
      id: '/_authenticated/entregador/ativos'
      path: '/ativos'
      fullPath: '/entregador/ativos'
      preLoaderRoute: typeof AuthenticatedEntregadorAtivosRouteImport
      parentRoute: typeof AuthenticatedEntregadorRouteRoute
    }
    '/_authenticated/admin/tarifas': {
      id: '/_authenticated/admin/tarifas'
      path: '/tarifas'
      fullPath: '/admin/tarifas'
      preLoaderRoute: typeof AuthenticatedAdminTarifasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/suporte': {
      id: '/_authenticated/admin/suporte'
      path: '/suporte'
      fullPath: '/admin/suporte'
      preLoaderRoute: typeof AuthenticatedAdminSuporteRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/roteirizacao': {
      id: '/_authenticated/admin/roteirizacao'
      path: '/roteirizacao'
      fullPath: '/admin/roteirizacao'
      preLoaderRoute: typeof AuthenticatedAdminRoteirizacaoRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/planos': {
      id: '/_authenticated/admin/planos'
      path: '/planos'
      fullPath: '/admin/planos'
      preLoaderRoute: typeof AuthenticatedAdminPlanosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pedidos': {
      id: '/_authenticated/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AuthenticatedAdminPedidosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/password-reset': {
      id: '/_authenticated/admin/password-reset'
      path: '/password-reset'
      fullPath: '/admin/password-reset'
      preLoaderRoute: typeof AuthenticatedAdminPasswordResetRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/notificacao-som-loja': {
      id: '/_authenticated/admin/notificacao-som-loja'
      path: '/notificacao-som-loja'
      fullPath: '/admin/notificacao-som-loja'
      preLoaderRoute: typeof AuthenticatedAdminNotificacaoSomLojaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/notificacao-som': {
      id: '/_authenticated/admin/notificacao-som'
      path: '/notificacao-som'
      fullPath: '/admin/notificacao-som'
      preLoaderRoute: typeof AuthenticatedAdminNotificacaoSomRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/lojas': {
      id: '/_authenticated/admin/lojas'
      path: '/lojas'
      fullPath: '/admin/lojas'
      preLoaderRoute: typeof AuthenticatedAdminLojasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/financeiro': {
      id: '/_authenticated/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AuthenticatedAdminFinanceiroRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/entregadores': {
      id: '/_authenticated/admin/entregadores'
      path: '/entregadores'
      fullPath: '/admin/entregadores'
      preLoaderRoute: typeof AuthenticatedAdminEntregadoresRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/creditos-entregador': {
      id: '/_authenticated/admin/creditos-entregador'
      path: '/creditos-entregador'
      fullPath: '/admin/creditos-entregador'
      preLoaderRoute: typeof AuthenticatedAdminCreditosEntregadorRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/contratos': {
      id: '/_authenticated/admin/contratos'
      path: '/contratos'
      fullPath: '/admin/contratos'
      preLoaderRoute: typeof AuthenticatedAdminContratosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/categorias': {
      id: '/_authenticated/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AuthenticatedAdminCategoriasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/branding': {
      id: '/_authenticated/admin/branding'
      path: '/branding'
      fullPath: '/admin/branding'
      preLoaderRoute: typeof AuthenticatedAdminBrandingRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/app-apk': {
      id: '/_authenticated/admin/app-apk'
      path: '/app-apk'
      fullPath: '/admin/app-apk'
      preLoaderRoute: typeof AuthenticatedAdminAppApkRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/anuncios': {
      id: '/_authenticated/admin/anuncios'
      path: '/anuncios'
      fullPath: '/admin/anuncios'
      preLoaderRoute: typeof AuthenticatedAdminAnunciosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/alertas': {
      id: '/_authenticated/admin/alertas'
      path: '/alertas'
      fullPath: '/admin/alertas'
      preLoaderRoute: typeof AuthenticatedAdminAlertasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/admins': {
      id: '/_authenticated/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AuthenticatedAdminAdminsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/mp-webhook/$lojaId': {
      id: '/api/public/mp-webhook/$lojaId'
      path: '/$lojaId'
      fullPath: '/api/public/mp-webhook/$lojaId'
      preLoaderRoute: typeof ApiPublicMpWebhookLojaIdRouteImport
      parentRoute: typeof ApiPublicMpWebhookRoute
    }
    '/api/public/hooks/mp-poll-pendentes': {
      id: '/api/public/hooks/mp-poll-pendentes'
      path: '/api/public/hooks/mp-poll-pendentes'
      fullPath: '/api/public/hooks/mp-poll-pendentes'
      preLoaderRoute: typeof ApiPublicHooksMpPollPendentesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAdminsRoute: typeof AuthenticatedAdminAdminsRoute
  AuthenticatedAdminAlertasRoute: typeof AuthenticatedAdminAlertasRoute
  AuthenticatedAdminAnunciosRoute: typeof AuthenticatedAdminAnunciosRoute
  AuthenticatedAdminAppApkRoute: typeof AuthenticatedAdminAppApkRoute
  AuthenticatedAdminBrandingRoute: typeof AuthenticatedAdminBrandingRoute
  AuthenticatedAdminCategoriasRoute: typeof AuthenticatedAdminCategoriasRoute
  AuthenticatedAdminContratosRoute: typeof AuthenticatedAdminContratosRoute
  AuthenticatedAdminCreditosEntregadorRoute: typeof AuthenticatedAdminCreditosEntregadorRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminEntregadoresRoute: typeof AuthenticatedAdminEntregadoresRoute
  AuthenticatedAdminFinanceiroRoute: typeof AuthenticatedAdminFinanceiroRoute
  AuthenticatedAdminLojasRoute: typeof AuthenticatedAdminLojasRoute
  AuthenticatedAdminNotificacaoSomRoute: typeof AuthenticatedAdminNotificacaoSomRoute
  AuthenticatedAdminNotificacaoSomLojaRoute: typeof AuthenticatedAdminNotificacaoSomLojaRoute
  AuthenticatedAdminPasswordResetRoute: typeof AuthenticatedAdminPasswordResetRoute
  AuthenticatedAdminPedidosRoute: typeof AuthenticatedAdminPedidosRoute
  AuthenticatedAdminPlanosRoute: typeof AuthenticatedAdminPlanosRoute
  AuthenticatedAdminRoteirizacaoRoute: typeof AuthenticatedAdminRoteirizacaoRoute
  AuthenticatedAdminSuporteRoute: typeof AuthenticatedAdminSuporteRoute
  AuthenticatedAdminTarifasRoute: typeof AuthenticatedAdminTarifasRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAdminsRoute: AuthenticatedAdminAdminsRoute,
    AuthenticatedAdminAlertasRoute: AuthenticatedAdminAlertasRoute,
    AuthenticatedAdminAnunciosRoute: AuthenticatedAdminAnunciosRoute,
    AuthenticatedAdminAppApkRoute: AuthenticatedAdminAppApkRoute,
    AuthenticatedAdminBrandingRoute: AuthenticatedAdminBrandingRoute,
    AuthenticatedAdminCategoriasRoute: AuthenticatedAdminCategoriasRoute,
    AuthenticatedAdminContratosRoute: AuthenticatedAdminContratosRoute,
    AuthenticatedAdminCreditosEntregadorRoute:
      AuthenticatedAdminCreditosEntregadorRoute,
    AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
    AuthenticatedAdminEntregadoresRoute: AuthenticatedAdminEntregadoresRoute,
    AuthenticatedAdminFinanceiroRoute: AuthenticatedAdminFinanceiroRoute,
    AuthenticatedAdminLojasRoute: AuthenticatedAdminLojasRoute,
    AuthenticatedAdminNotificacaoSomRoute:
      AuthenticatedAdminNotificacaoSomRoute,
    AuthenticatedAdminNotificacaoSomLojaRoute:
      AuthenticatedAdminNotificacaoSomLojaRoute,
    AuthenticatedAdminPasswordResetRoute: AuthenticatedAdminPasswordResetRoute,
    AuthenticatedAdminPedidosRoute: AuthenticatedAdminPedidosRoute,
    AuthenticatedAdminPlanosRoute: AuthenticatedAdminPlanosRoute,
    AuthenticatedAdminRoteirizacaoRoute: AuthenticatedAdminRoteirizacaoRoute,
    AuthenticatedAdminSuporteRoute: AuthenticatedAdminSuporteRoute,
    AuthenticatedAdminTarifasRoute: AuthenticatedAdminTarifasRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedEntregadorRouteRouteChildren {
  AuthenticatedEntregadorAtivosRoute: typeof AuthenticatedEntregadorAtivosRoute
  AuthenticatedEntregadorCarteiraRoute: typeof AuthenticatedEntregadorCarteiraRoute
  AuthenticatedEntregadorDisponiveisRoute: typeof AuthenticatedEntregadorDisponiveisRoute
  AuthenticatedEntregadorHistoricoRoute: typeof AuthenticatedEntregadorHistoricoRoute
  AuthenticatedEntregadorMensalidadeRoute: typeof AuthenticatedEntregadorMensalidadeRoute
  AuthenticatedEntregadorPerfilRoute: typeof AuthenticatedEntregadorPerfilRoute
  AuthenticatedEntregadorTurnosRoute: typeof AuthenticatedEntregadorTurnosRoute
  AuthenticatedEntregadorIndexRoute: typeof AuthenticatedEntregadorIndexRoute
}

const AuthenticatedEntregadorRouteRouteChildren: AuthenticatedEntregadorRouteRouteChildren =
  {
    AuthenticatedEntregadorAtivosRoute: AuthenticatedEntregadorAtivosRoute,
    AuthenticatedEntregadorCarteiraRoute: AuthenticatedEntregadorCarteiraRoute,
    AuthenticatedEntregadorDisponiveisRoute:
      AuthenticatedEntregadorDisponiveisRoute,
    AuthenticatedEntregadorHistoricoRoute:
      AuthenticatedEntregadorHistoricoRoute,
    AuthenticatedEntregadorMensalidadeRoute:
      AuthenticatedEntregadorMensalidadeRoute,
    AuthenticatedEntregadorPerfilRoute: AuthenticatedEntregadorPerfilRoute,
    AuthenticatedEntregadorTurnosRoute: AuthenticatedEntregadorTurnosRoute,
    AuthenticatedEntregadorIndexRoute: AuthenticatedEntregadorIndexRoute,
  }

const AuthenticatedEntregadorRouteRouteWithChildren =
  AuthenticatedEntregadorRouteRoute._addFileChildren(
    AuthenticatedEntregadorRouteRouteChildren,
  )

interface AuthenticatedLojaRouteRouteChildren {
  AuthenticatedLojaAgendamentosRoute: typeof AuthenticatedLojaAgendamentosRoute
  AuthenticatedLojaConfiguracoesRoute: typeof AuthenticatedLojaConfiguracoesRoute
  AuthenticatedLojaDashboardRoute: typeof AuthenticatedLojaDashboardRoute
  AuthenticatedLojaEntregadoresRoute: typeof AuthenticatedLojaEntregadoresRoute
  AuthenticatedLojaFinanceiroRoute: typeof AuthenticatedLojaFinanceiroRoute
  AuthenticatedLojaNovoPedidoRoute: typeof AuthenticatedLojaNovoPedidoRoute
  AuthenticatedLojaPedidosRoute: typeof AuthenticatedLojaPedidosRoute
  AuthenticatedLojaProdutosRoute: typeof AuthenticatedLojaProdutosRoute
  AuthenticatedLojaSuporteRoute: typeof AuthenticatedLojaSuporteRoute
  AuthenticatedLojaIndexRoute: typeof AuthenticatedLojaIndexRoute
}

const AuthenticatedLojaRouteRouteChildren: AuthenticatedLojaRouteRouteChildren =
  {
    AuthenticatedLojaAgendamentosRoute: AuthenticatedLojaAgendamentosRoute,
    AuthenticatedLojaConfiguracoesRoute: AuthenticatedLojaConfiguracoesRoute,
    AuthenticatedLojaDashboardRoute: AuthenticatedLojaDashboardRoute,
    AuthenticatedLojaEntregadoresRoute: AuthenticatedLojaEntregadoresRoute,
    AuthenticatedLojaFinanceiroRoute: AuthenticatedLojaFinanceiroRoute,
    AuthenticatedLojaNovoPedidoRoute: AuthenticatedLojaNovoPedidoRoute,
    AuthenticatedLojaPedidosRoute: AuthenticatedLojaPedidosRoute,
    AuthenticatedLojaProdutosRoute: AuthenticatedLojaProdutosRoute,
    AuthenticatedLojaSuporteRoute: AuthenticatedLojaSuporteRoute,
    AuthenticatedLojaIndexRoute: AuthenticatedLojaIndexRoute,
  }

const AuthenticatedLojaRouteRouteWithChildren =
  AuthenticatedLojaRouteRoute._addFileChildren(
    AuthenticatedLojaRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedEntregadorRouteRoute: typeof AuthenticatedEntregadorRouteRouteWithChildren
  AuthenticatedLojaRouteRoute: typeof AuthenticatedLojaRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedEntregadorRouteRoute:
    AuthenticatedEntregadorRouteRouteWithChildren,
  AuthenticatedLojaRouteRoute: AuthenticatedLojaRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiPublicMpWebhookRouteChildren {
  ApiPublicMpWebhookLojaIdRoute: typeof ApiPublicMpWebhookLojaIdRoute
}

const ApiPublicMpWebhookRouteChildren: ApiPublicMpWebhookRouteChildren = {
  ApiPublicMpWebhookLojaIdRoute: ApiPublicMpWebhookLojaIdRoute,
}

const ApiPublicMpWebhookRouteWithChildren =
  ApiPublicMpWebhookRoute._addFileChildren(ApiPublicMpWebhookRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  BaixarAppRoute: BaixarAppRoute,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  CSlugRoute: CSlugRoute,
  ClientesCidadeRoute: ClientesCidadeRoute,
  LojaSlugRoute: LojaSlugRoute,
  RastreioPedidoIdRoute: RastreioPedidoIdRoute,
  ClientesIndexRoute: ClientesIndexRoute,
  ApiPublicManifestDotwebmanifestRoute: ApiPublicManifestDotwebmanifestRoute,
  ApiPublicMpWebhookRoute: ApiPublicMpWebhookRouteWithChildren,
  ApiPublicMpWebhookEntregadorRoute: ApiPublicMpWebhookEntregadorRoute,
  ApiPublicMpWebhookPlataformaRoute: ApiPublicMpWebhookPlataformaRoute,
  ApiPublicPwaIconDotpngRoute: ApiPublicPwaIconDotpngRoute,
  ApiPublicSendPushRoute: ApiPublicSendPushRoute,
  ApiPublicHooksMpPollPendentesRoute: ApiPublicHooksMpPollPendentesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
